/* ==========================================================
   CONTENIDO DE VOIA
   Aquí se edita todo el texto de los destinos y las preguntas
   frecuentes. Las fotos son de Unsplash (licencia libre) y se
   identifican por su código "photo-...".

   Para agregar un itinerario a un destino, llena su campo
   "itinerario" con una lista de días (mira Bali como ejemplo).
   Para ocultar un destino como "Próximamente" (sin página),
   agrega  proximamente: true  y  meta: "Próximamente".
   ========================================================== */

const DESTINOS = [
  /* ---------------------- NACIONALES ---------------------- */
  {
    slug: "baja-california-sur",
    grupo: "nacionales",
    nombre: "Baja California Sur",
    meta: "La Paz, La Ventana y Cabo Pulmo · 7 noches",
    duracion: "8 días / 7 noches",
    temporada: "Abril – mayo",
    ubicacion: "La Paz, La Ventana y Cabo Pulmo",
    fechas: "No disponibles por el momento",
    tagline: "Móbulas, lobos marinos y vida salvaje en el Mar de Cortés",
    tile: "media/bajamedia/mobula1-tile.jpg",
    tilePos: "50% 50%",
    hero: "media/bajamedia/mobula1.jpg", // portada de la página
    citaFoto: "photo-1698472505070-6d3b90afb530", // fondo de la frase (no es de la galería)
    galeria: [
      "photo-1565413294262-fa587c396965",
      "photo-1698472505070-6d3b90afb530",
      "photo-1615695478392-af177ac550b9",
      "photo-1605379380320-920cb561bd55",
      "photo-1698792726005-761c35c8ff56",
    ],
    descripcion: [
      "Este viaje recorre el sur de Baja California Sur en siete noches, de La Paz a La Ventana y Cabo Pulmo. Es una costa donde el desierto se encuentra con el Mar de Cortés y donde, en abril y mayo, el cambio de temperatura del agua atrae a mucha vida marina.",
      "Empezamos en La Paz con un día en la isla Espíritu Santo para nadar con lobos marinos. Seguimos con tres días de safari en La Ventana, en plena temporada de móbulas, y terminamos en Cabo Pulmo, un parque nacional marino famoso por su arrecife. Cada salida depende del mar: lo mejor es ir sin expectativas y dejar que la naturaleza sorprenda.",
      "Los animales son libres. Pueden aparecer móbulas, delfines, ballenas o incluso orcas, pero nunca se puede garantizar. Por eso ponemos su bienestar por encima de cualquier foto.",
    ],
    cita: "Entre el desierto y el mar, la vida salvaje marca el rumbo.",
    destacados: [
      "Snorkel con lobos marinos en la isla Espíritu Santo",
      "Tres días de safari en La Ventana en temporada de móbulas",
      "Parque Nacional Cabo Pulmo, con jureles y tiburones toro",
      "Un día libre para descansar, caminar o bucear",
    ],
    itinerario: [
      { dia: 1, titulo: "Llegada a La Paz", lugar: "La Paz", plan: ["Recogida en el aeropuerto y traslado al hotel, donde pasamos dos noches.", "Paseo por el centro histórico y el malecón.", "Presentación del equipo de guías y de las actividades de la semana.", "Atardecer en un rooftop con vista al mar. Si el grupo tiene energía, visita al museo de la ballena."] },
      { dia: 2, titulo: "Isla Espíritu Santo", lugar: "La Paz", plan: ["Día completo en barco privado.", "Snorkel con lobos marinos en La Lobera.", "Parada en playas para comer ceviche fresco y comida típica.", "Posible snorkel con tiburón ballena en El Mogote, si el parque nacional está abierto.", "Safari alrededor de la isla, paseo por La Paz y atardecer en el malecón."] },
      { dia: 3, titulo: "Primer safari en La Ventana", lugar: "La Paz – La Ventana", plan: ["Traslado privado de una hora a La Ventana.", "Primer día de safari en el mar: pueden aparecer móbulas, delfines, orcas y distintas especies de ballenas.", "Check-in en el hotel y cena en grupo."] },
      { dia: 4, titulo: "Segundo safari", lugar: "La Ventana", plan: ["Día completo de safari en el mar.", "En abril cambia la temperatura del agua y muchas especies llegan a la zona en busca de refugio y comida, así que cada salida es distinta."] },
      { dia: 5, titulo: "Tercer safari", lugar: "La Ventana", plan: ["Tercer día de safari en busca de móbulas y otros grandes animales del mar abierto.", "Abril es conocido en esta costa por las congregaciones de móbulas y, con suerte, por el paso de la ballena azul."] },
      { dia: 6, titulo: "Rumbo a Cabo Pulmo", lugar: "La Ventana – Cabo Pulmo", plan: ["Traslado de unas dos horas al Parque Nacional Cabo Pulmo y check-in en las cabañas, donde pasamos las dos últimas noches.", "Safari de medio día en el parque, conocido por sus jureles y tiburones toro.", "Comida en un local de tacos del parque."] },
      { dia: 7, titulo: "Día libre en Cabo Pulmo", lugar: "Cabo Pulmo", plan: ["Día libre para descansar, disfrutar la playa y las cabañas o caminar por las montañas del parque.", "Opcional, si hay buena visibilidad: dos inmersiones de buceo con tanque (con costo aparte)."] },
      { dia: 8, titulo: "Despedida", lugar: "Cabo Pulmo – La Paz", plan: ["Regreso a La Paz en transfer privado.", "Según el horario de los vuelos, paramos en un campo de cactus o damos un último paseo y hacemos compras en el centro.", "Traslado al aeropuerto."] },
    ],
    nota: "Los avistamientos de fauna silvestre no están garantizados. Las salidas pueden cambiar según el clima y las condiciones del mar.",
  },
  {
    slug: "riviera-maya",
    grupo: "nacionales",
    nombre: "Riviera Maya",
    meta: "Cenotes · Tiburón toro · Cultura maya",
    duracion: "7 días",
    ubicacion: "Riviera Maya, Quintana Roo",
    fechas: "No disponibles por el momento",
    tagline: "Cenotes, tiburones toro y cultura maya",
    tile: "media/rivieramedia/cenotes1-tile.jpg",
    tilePos: "45% 50%",
    hero: "media/rivieramedia/tiburontoro1.jpg", // portada de la página (foto grande, sin recortar de más)
    galeria: [
      { src: "media/rivieramedia/web/tiburontoro1.jpg", w: 1260, h: 900, alt: "Tiburón toro nadando cerca del fondo arenoso, con otro tiburón al fondo", credito: "FOTO: MarAlliance" },
      "photo-1719941463960-f3310fe64e46",
      "photo-1546838849-6eb6269ae2db",
      "photo-1518638150340-f706e86654de",
      "photo-1640617547871-15e4fb41d0c5",
    ],
    descripcion: [
      "Bajo la selva de la península de Yucatán corre uno de los sistemas de ríos subterráneos más grandes del mundo. Los cenotes, que se abren cuando se hunde la roca caliza, fueron lugares sagrados para los mayas y hoy nos permiten bucear entre luz, agua cristalina y formaciones milenarias.",
      "Este viaje reúne tres experiencias en siete días: buceo en cenotes, una inmersión con tiburones toro frente a Playa del Carmen y una visita a una comunidad maya. Ahí conocemos su cultura y su manera de cuidar el territorio, de la mano de quienes viven en él.",
      "Los tiburones toro son animales salvajes y los observamos con operadores especializados. La seguridad de las personas y el respeto por los animales van siempre primero.",
    ],
    cita: "Bajo la selva, los cenotes guardan historias del mundo maya.",
    destacados: [
      "Buceo en cenotes",
      "Inmersión con tiburones toro en Playa del Carmen",
      "Experiencia con una comunidad maya",
    ],
    itinerario: null,
    nota: "Los avistamientos de fauna silvestre no están garantizados. Los requisitos de certificación de buceo se confirman al reservar.",
  },
  {
    slug: "veracruz",
    grupo: "nacionales",
    nombre: "Veracruz",
    meta: "Jalcomulco · Sótano de Popocatl",
    duracion: "3 días por ruta",
    ubicacion: "Veracruz, México",
    fechas: "No disponibles por el momento",
    tagline: "Cavernas, cascadas y río en el interior veracruzano",
    tile: "media/veracruzmedia/jalco1-3-tile.jpg",
    tilePos: "50% 55%",
    hero: "media/veracruzmedia/sotano1.jpg", // portada de la página
    citaFoto: "photo-1511936606692-5e0d73f6b638", // fondo de la frase (no es de la galería)
    galeria: [
      { src: "media/veracruzmedia/sotano1.jpg", w: 1500, h: 1001, alt: "Persona bajando en rappel junto a una cascada dentro del Sótano de Popocatl" },
      { src: "media/veracruzmedia/web/sotano2.jpg", w: 960, h: 640, alt: "Grupo en una balsa azul atravesando rápidos en el río" },
      { src: "media/veracruzmedia/sotano3.jpg", w: 1440, h: 960, alt: "Dos personas con casco frente al bosque, junto a la entrada de la cueva" },
      { src: "media/veracruzmedia/sotano4.jpg", w: 1440, h: 1800, alt: "Cuerda con mosquetón y nudo frente a una pared de roca con bruma" },
      { src: "media/veracruzmedia/web/sotano5.jpg", w: 960, h: 640, alt: "Balsa azul con un grupo entre rápidos de espuma blanca" },
      { src: "media/veracruzmedia/sotano6.jpg", w: 1440, h: 1800, alt: "Dos personas descendiendo por cuerdas junto a una pared de roca y una cascada" },
      { src: "media/veracruzmedia/sotano7.jpg", w: 1440, h: 1800, alt: "Persona descendiendo en rappel por la boca de una cueva" },
      { src: "media/veracruzmedia/web/sotano8.jpg", w: 960, h: 640, alt: "Grupo celebrando con los brazos en alto en una balsa de rafting" },
      { src: "media/veracruzmedia/sotano9.jpg", w: 1440, h: 1800, alt: "Cascada cayendo por una estrecha grieta de roca cubierta de musgo" },
      { src: "media/veracruzmedia/sotano10.jpg", w: 960, h: 1200, alt: "Cascada dentro de una cueva, iluminada por un rayo de luz" },
      { src: "media/veracruzmedia/web/sotano11.jpg", w: 960, h: 640, alt: "Balsa entre rápidos fuertes junto a un árbol de raíces enormes" },
    ],
    descripcion: [
      "Veracruz es mucho más que costa. Hacia el interior, entre montañas, selva y ríos, hay lugares pensados para quienes quieren aventura y contacto directo con la naturaleza, a pocas horas de casa.",
      "Ofrecemos dos rutas de tres días. Una baja a una caverna con cascada subterránea en la Sierra de Zongolica; la otra recorre uno de los ríos más conocidos de México para el rafting. Son viajes cortos, intensos y con guías que conocen bien el terreno.",
    ],
    cita: "Donde el agua abre camino entre la selva.",
    rutas: [
      {
        nombre: "Ruta 1 · Sótano de Popocatl",
        duracion: "3 días",
        descripcion: [
          "En la Sierra de Zongolica, una caverna de más de 40 metros de diámetro recibe una cascada que cae cerca de 60 metros hasta un río subterráneo. Popocatl significa «agua que humea» en náhuatl, por la bruma que levanta el agua al caer.",
          "Se llega después de una caminata corta por el bosque. El descenso se hace con rappel, con equipo especializado y guías acreditados.",
        ],
        itinerario: null,
      },
      {
        nombre: "Ruta 2 · Jalcomulco",
        duracion: "3 días",
        descripcion: [
          "Jalcomulco, sobre el río La Antigua, es conocido como la capital del rafting en México. El río corre entre selva y cañones, con rápidos para distintos niveles.",
          "El pueblo es un buen punto de partida para remar, caminar, hacer rappel o descansar junto al agua, en un entorno verde y tranquilo.",
        ],
        itinerario: null,
      },
    ],
    nota: "Las actividades dependen del nivel del agua y del clima. Te confirmamos requisitos y equipo al reservar.",
  },

  /* ------------------- INTERNACIONALES ------------------- */
  {
    slug: "bali",
    quiz: true, // tiene test "¿Este viaje es para ti?" (ver quiz-data.js)
    grupo: "internacionales",
    nombre: "Bali",
    meta: "Indonesia · 15 días",
    duracion: "15 días",
    ubicacion: "Bali, Indonesia",
    fechas: "22 de mayo – 5 de junio de 2027",
    marcaAgua: "AF Photography", // aparece en chiquito al pasar el cursor sobre una foto de la galería (solo escritorio)
    tagline: "Arrozales, templos, volcanes y mantas gigantes",
    tile: "photo-1555400038-63f5ba517a47",
    hero: "media/balimedia/web/baligaleria-02-hero.jpg", // foto grande del encabezado
    citaFoto: "media/balimedia/web/baligaleria-20-fondo.jpg", // foto de fondo de la frase
    galeria: [
      { src: "media/balimedia/web/baligaleria-01.jpg", w: 427, h: 640, alt: "Mujer con sombrero cónico caminando entre arrozales en terrazas" },
      { src: "media/balimedia/web/baligaleria-02.jpg", w: 1138, h: 640, alt: "Vista aérea de los acantilados y la playa de Kelingking, en Nusa Penida" },
      { src: "media/balimedia/web/baligaleria-03.jpg", w: 427, h: 640, alt: "Buzo nadando sobre un arrecife de coral con una tortuga" },
      { src: "media/balimedia/web/baligaleria-05.jpg", w: 960, h: 640, alt: "Grupo de viajeros caminando por un sendero entre arrozales" },
      { src: "media/balimedia/web/baligaleria-06.jpg", w: 480, h: 640, alt: "Dos personas frente a una cascada entre rocas" },
      { src: "media/balimedia/web/baligaleria-07.jpg", w: 960, h: 640, alt: "Surfista sobre una ola turquesa" },
      { src: "media/balimedia/web/baligaleria-15.jpg", w: 427, h: 640, alt: "Mono sobre un techo entre los árboles" },
      { src: "media/balimedia/web/baligaleria-04.jpg", w: 426, h: 640, alt: "Manta raya nadando sobre el arrecife" },
      { src: "media/balimedia/web/baligaleria-08.jpg", w: 960, h: 640, alt: "Dos viajeros sonriendo entre la vegetación tropical" },
      { src: "media/balimedia/web/baligaleria-12.jpg", w: 1142, h: 640, alt: "Grupo de rafting con los brazos en alto en un río" },
      { src: "media/balimedia/web/baligaleria-09.jpg", w: 427, h: 640, alt: "Ceremonia en un templo balinés con ofrendas" },
      { src: "media/balimedia/web/baligaleria-10.jpg", w: 426, h: 640, alt: "Grupo de viajeros frente a la puerta de un templo balinés" },
      { src: "media/balimedia/web/baligaleria-11.jpg", w: 960, h: 640, alt: "Grupo de amigas viendo el amanecer sobre la selva" },
      { src: "media/balimedia/web/baligaleria-13.jpg", w: 1138, h: 640, alt: "Vista aérea de campos de arroz en terrazas" },
      { src: "media/balimedia/web/baligaleria-14.jpg", w: 427, h: 640, alt: "Macacos sentados en el bosque de los monos" },
      { src: "media/balimedia/web/baligaleria-16.jpg", w: 960, h: 639, alt: "Manta raya nadando en aguas azules" },
      { src: "media/balimedia/web/baligaleria-17.jpg", w: 960, h: 640, alt: "Arrecife de coral con peces" },
      { src: "media/balimedia/web/baligaleria-18.jpg", w: 1138, h: 640, alt: "Vista aérea de la costa de Kelingking y sus rocas" },
      { src: "media/balimedia/web/baligaleria-19.jpg", w: 427, h: 640, alt: "Viajeros sobre un vehículo 4x4 bajo un cielo nublado" },
      { src: "media/balimedia/web/baligaleria-20.jpg", w: 960, h: 640, alt: "Valle verde con arrozales y palmeras visto desde lo alto" },
      { src: "media/balimedia/web/baligaleria-21.jpg", w: 427, h: 640, alt: "Ceremonia balinesa con trajes tradicionales y dorados" },
      { src: "media/balimedia/web/baligaleria-22.jpg", w: 427, h: 640, alt: "Arrozales en terrazas bajo un cielo claro" },
      { src: "media/balimedia/web/baligaleria-23.jpg", w: 960, h: 640, alt: "Grupo de viajeras en un mirador de madera entre palmeras" },
      { src: "media/balimedia/web/baligaleria-24.jpg", w: 427, h: 640, alt: "Columpio colgando de una palmera en la selva" },
      { src: "media/balimedia/web/baligaleria-26.jpg", w: 479, h: 640, alt: "Pez payaso entre anémonas" },
      { src: "media/balimedia/web/baligaleria-28.jpg", w: 427, h: 640, alt: "Pareja caminando por un sendero entre arrozales" },
      { src: "media/balimedia/web/baligaleria-29.jpg", w: 480, h: 640, alt: "Grupo de viajeros sentados entre rocas cubiertas de vegetación" },
      { src: "media/balimedia/web/baligaleria-30.jpg", w: 427, h: 640, alt: "Dos personas caminando entre arrozales" },
      { src: "media/balimedia/web/baligaleria-31.jpg", w: 360, h: 640, alt: "Vista aérea del acantilado de Kelingking con su playa" },
      { src: "media/balimedia/web/baligaleria-32.jpg", w: 960, h: 640, alt: "Templo sobre una roca en el mar al atardecer" },
      { src: "media/balimedia/web/baligaleria-33.jpg", w: 480, h: 640, alt: "Grupo de viajeros en una playa de arena blanca" },
      { src: "media/balimedia/web/baligaleria-34.jpg", w: 960, h: 640, alt: "Persona de pie en una colina verde frente a arrozales" },
      { src: "media/balimedia/web/baligaleria-35.jpg", w: 360, h: 640, alt: "Mujer balinesa cargando una ofrenda sobre la cabeza" },
      { src: "media/balimedia/web/baligaleria-36.jpg", w: 426, h: 640, alt: "Dos músicos con trajes tradicionales y gongs" },
      { src: "media/balimedia/web/baligaleria-37.jpg", w: 960, h: 640, alt: "Selva tropical densa con palmeras y plantas de plátano" },
      { src: "media/balimedia/web/baligaleria-38.jpg", w: 960, h: 640, alt: "Buzos sobre un arrecife de coral, con una tortuga marina" },
      { src: "media/balimedia/web/baligaleria-39.jpg", w: 427, h: 640, alt: "Grupo de viajeros posando en un pasaje de piedra, con una gran estatua al fondo" },
      { src: "media/balimedia/web/baligaleria-40.jpg", w: 427, h: 640, alt: "Macaco comiendo sobre un muro cubierto de musgo" },
      { src: "media/balimedia/web/baligaleria-41.jpg", w: 480, h: 640, alt: "Mantarraya nadando en aguas azules" },
      { src: "media/balimedia/web/baligaleria-43.jpg", w: 427, h: 640, alt: "Músico tradicional frente a un instrumento de madera decorado sobre una alfombra roja" },
      { src: "media/balimedia/web/baligaleria-44.jpg", w: 960, h: 640, alt: "Arrozales en terrazas bajo un cielo nublado" },
      { src: "media/balimedia/web/baligaleria-45.jpg", w: 442, h: 640, alt: "Anémona de mar sobre un arrecife, con el océano azul de fondo" },
      { src: "media/balimedia/web/baligaleria-46.jpg", w: 427, h: 640, alt: "Viajera de pie entre arrozales en terrazas" },
      { src: "media/balimedia/web/baligaleria-47.jpg", w: 960, h: 640, alt: "Templo de varios techos a la orilla de un lago entre la niebla" },
      { src: "media/balimedia/web/baligaleria-48.jpg", w: 427, h: 640, alt: "Grupo de viajeros posando en un templo balinés" },
      { src: "media/balimedia/web/baligaleria-49.jpg", w: 427, h: 640, alt: "Selva espesa con plátanos y vegetación tropical" },
      { src: "media/balimedia/web/baligaleria-50.jpg", w: 427, h: 640, alt: "Dos personas tocando un instrumento tradicional sobre una alfombra roja" },
      { src: "media/balimedia/web/baligaleria-51.jpg", w: 427, h: 640, alt: "Pareja entre los arrozales en terrazas" },
      { src: "media/balimedia/web/baligaleria-52.jpg", w: 960, h: 640, alt: "Viajeros riendo y chocando las manos junto a una estructura de madera en la selva" },
      { src: "media/balimedia/web/baligaleria-53.jpg", w: 427, h: 640, alt: "Tres viajeros junto a un campo de arroz y bambú" },
      { src: "media/balimedia/web/baligaleria-54.jpg", w: 426, h: 640, alt: "Templo con techo de varios niveles sobre un lago con nenúfares" },
      { src: "media/balimedia/web/baligaleria-55.jpg", w: 426, h: 640, alt: "Mantarraya nadando sobre un arrecife de coral" },
      { src: "media/balimedia/web/baligaleria-56.jpg", w: 427, h: 640, alt: "Viajero con los brazos abiertos entre arrozales en terrazas" },
      { src: "media/balimedia/web/baligaleria-57.jpg", w: 960, h: 640, alt: "Tres viajeros posando junto a los arrozales" },
      { src: "media/balimedia/web/baligaleria-58.jpg", w: 427, h: 640, alt: "Pareja bajando las escaleras de una puerta de templo balinés" },
      { src: "media/balimedia/web/baligaleria-59.jpg", w: 427, h: 640, alt: "Santuario balinés de piedra tallada rodeado de vegetación" },
      { src: "media/balimedia/web/baligaleria-60.jpg", w: 427, h: 640, alt: "Buceador a pulmón nadando bajo la superficie del mar" },
      { src: "media/balimedia/web/baligaleria-61.jpg", w: 960, h: 640, alt: "Grupo de viajeros posando entre arrozales en terrazas" },
      { src: "media/balimedia/web/baligaleria-62.jpg", w: 427, h: 640, alt: "Grupo caminando por el patio de un templo, vestidos con sarong" },
      { src: "media/balimedia/web/baligaleria-63.jpg", w: 480, h: 640, alt: "Tiburón de arrecife de cerca, sobre un fondo oscuro" },
      { src: "media/balimedia/web/baligaleria-64.jpg", w: 960, h: 640, alt: "Arrecife de coral colorido bajo el agua" },
      { src: "media/balimedia/web/baligaleria-65.jpg", w: 960, h: 640, alt: "Grupo de viajeros en una colina entre arrozales" },
      { src: "media/balimedia/web/baligaleria-66.jpg", w: 427, h: 640, alt: "Grupo de viajeros en un mirador sobre el acantilado de Kelingking" },
      { src: "media/balimedia/web/baligaleria-67.jpg", w: 960, h: 640, alt: "Grupo de viajeros sonriendo a bordo de un barco" },
      { src: "media/balimedia/web/baligaleria-68.jpg", w: 960, h: 640, alt: "Arrozales en terrazas con un hotel en lo alto de la colina" },
      { src: "media/balimedia/web/baligaleria-69.jpg", w: 960, h: 639, alt: "Cría de tortuga marina sobre la arena" },
    ],
    descripcion: [
      "Imagina despertar rodeado de arrozales, ver amanecer desde la cima de un volcán y, unos días después, nadar junto a mantas gigantes. Bali es una isla de contrastes donde naturaleza, aventura y cultura conviven con una forma de vida profundamente ligada al Tri Hita Karana: la búsqueda del equilibrio entre las personas, la naturaleza y lo espiritual.",
      "Durante quince días recorremos la isla comenzando en un rincón alejado de las rutas habituales. De ahí viajamos a Ubud, subimos al Monte Batur al amanecer, cruzamos a Nusa Penida para explorar la isla y nadar con mantas. Seguimos por el paraíso natural en las islas Gili y terminamos entre los acantilados y playas de Uluwatu.",
      "Viajamos en grupos pequeños, acompañados por guías locales y buscando experiencias que nos acerquen a la isla más allá de sus lugares más conocidos. Y dejamos espacio para esos momentos que no aparecen en ningún itinerario: coincidir con una ceremonia, descubrir un warung en el camino o terminar el día viendo el sol caer sobre el Índico.",
    ],
    cita: "Bali se entiende despacio: entre arrozales, ceremonias y amaneceres.",
    destacados: [
      "Bali rural en moto y los arrozales de Jatiluwih, Patrimonio de la Humanidad",
      "Ceremonia de purificación y templos de agua en Ubud",
      "Amanecer en el Monte Batur",
      "Snorkel y buceo con mantas en Nusa Penida",
      "Acantilados de Uluwatu, surf y danza Kecak",
    ],
    itinerario: [
      { dia: 1, titulo: "Llegada al Bali rural secreto", texto: "Recepción en el aeropuerto y traslado a una ubicación secreta en el corazón rural de Bali. Este lugar se revela únicamente a los viajeros confirmados para conservar su autenticidad y protegerlo del turismo masivo. Llegada y descanso en un ecolodge dentro de un arrozal privado." },
      { dia: 2, titulo: "Templos y paisajes del Bali rural", texto: "Recorreremos en moto los caminos del Bali más auténtico, entre arrozales, pequeñas comunidades y paisajes naturales. Visitaremos el templo Pura Luhur Batukaru antes de regresar al hotel." },
      { dia: 3, titulo: "Jatiluwih", texto: "Mañana libre para disfrutar del ecolodge. Por la tarde visitaremos los arrozales de Jatiluwih, declarados Patrimonio Mundial por la UNESCO, antes de continuar hacia Ubud. Check-in y cena en un warung local." },
      { dia: 4, titulo: "Monkey Forest y Kopi Luwak", texto: "Clase opcional de yoga por la mañana, seguida de una visita al Monkey Forest y una degustación de “kopi luwak”, el café más caro del mundo. Terminaremos el día contemplando el atardecer frente a un río y campos de arroz. ¡Los desplazamientos se realizarán en moto taxi para vivir Ubud como un local!" },
      { dia: 5, titulo: "Purificación balinesa y arrozales", texto: "Ceremonia tradicional de purificación en Beji Griya, un templo rodeado de cascadas y naturaleza. Después conoceremos los arrozales de Tegallalang y tendremos tiempo para comer y tomar fotografías. Cena libre." },
      { dia: 6, titulo: "Templos y Campuhan Ridge Walk", texto: "Visitaremos Tirta Empul y Gunung Kawi, dos de los complejos espirituales más importantes de Bali. Por la tarde se puede optar por 1) Recorrer Campuhan Ridge Walk y una sesión de sound healing o 2) Rafting." },
      { dia: 7, titulo: "Amanecer en el monte Batur", texto: "Salida de madrugada para ascender al monte Batur y contemplar el amanecer desde la cima. Después visitaremos el centro y mercado de Ubud. Tarde y noche libres para descansar." },
      { dia: 8, titulo: "Nusa Penida", texto: "Traslado desde Ubud y ferry hacia Nusa Penida. Al llegar realizaremos el check-in y tendremos tiempo libre para caminar junto al mar, visitar un beach club o descansar en la playa. Cena frente al mar." },
      { dia: 9, titulo: "Encuentro con las mantarrayas", texto: "Día dedicado a descubrir el mundo submarino de Nusa Penida. Se podrá elegir entre bucear en busca de mantarrayas, con sesión introductoria para quienes no tengan certificación, o realizar un tour de snorkel." },
      { dia: 10, titulo: "Kelingking Beach y Gili Trawangan", texto: "Salida temprano hacia Kelingking Beach. Será posible contemplar el paisaje desde lo alto o, de forma opcional, descender hasta la playa. Por la tarde regresaremos a Bali y tomaremos el traslado hacia Gili Trawangan." },
      { dia: 11, titulo: "Día libre en Gili Trawangan", texto: "Día libre en una isla sin coches ni motos, donde solo se circula a pie, en bicicleta o en carreta. Puedes bucear, hacer snorkel con tortugas, tomar una clase de yoga o simplemente disfrutar de la playa y el atardecer sobre el mar." },
      { dia: 12, titulo: "De Gili Trawangan a Uluwatu", texto: "Salida en barco hacia el puerto de Nusa Dua y traslado a Uluwatu, el último destino del viaje. Check-in y cena de llegada." },
      { dia: 13, titulo: "Surf y acantilados de Uluwatu", texto: "Clase opcional de surf en Padang Padang, o yoga. Después visitaremos Suluban Beach y comeremos en un warung local sobre los acantilados. Por la tarde, tiempo libre; por la noche, el templo de Uluwatu y la danza tradicional Kecak." },
      { dia: 14, titulo: "Día libre en Uluwatu", texto: "Día libre para disfrutar de las playas, practicar yoga, hacer surf, volar en parapente o descubrir los cafés de los acantilados." },
      { dia: 15, titulo: "Despedida de Bali", texto: "Check-out y traslado al aeropuerto para tomar el vuelo de regreso." },
    ],
    /* ----------------------------------------------------------
       PAGOS Y POLÍTICAS DE CANCELACIÓN de este viaje (sección "Pagos" de la página).
       Texto, montos y fechas tal cual los entregó VOIA. Para cambiar un monto o una fecha, edítalo aquí.
       Bloques: { h } subtítulo · { p } párrafo · { ul } lista · { aviso } recuadro destacado · { tabla } · { calendario }.
       En los textos: **negritas**, [texto](https://enlace) = enlace de afiliado (pestaña nueva, rel="sponsored noopener noreferrer")
       y los correos se vuelven enlace solos.
       ---------------------------------------------------------- */
    pagos: {
      subtitulo: "Viaje del 22 de mayo al 5 de junio de 2027 · voia.viajar@gmail.com",
      bloques: [
        {
          titulo: "Precios",
          abierto: true,
          contenido: [
            { h: "Precios por persona (IVA incluido)" },
            { tabla: {
                etiqueta: "Precios por paquete",
                cab: ["Paquete", "Early Bird (hasta el 25 dic 2026)", "Precio regular (desde enero 2027)"],
                filas: [
                  ["Divers Package", "$29,990 MXN / €1,480", "$35,000 MXN / €1,730"],
                  ["Adventure Package", "$28,990 MXN / €1,430", "$34,000 MXN / €1,680"],
                ],
            } },
            { p: "Precio por persona en habitación compartida para 2. ¿Viajas solo o sola? Escríbenos y te damos el precio de viajero individual." },
          ],
        },
        {
          titulo: "Calendario de pagos",
          contenido: [
            { calendario: {
                planes: [{ id: "early", nombre: "Early Bird" }, { id: "regular", nombre: "Precio regular" }],
                monedas: [{ id: "MXN", nombre: "MXN" }, { id: "EUR", nombre: "EUR" }],
                tablas: [
                  { plan: "early", moneda: "MXN", titulo: "Early Bird – Pesos mexicanos (MXN)", tabla: {
                    etiqueta: "Calendario de pagos Early Bird en pesos mexicanos",
                    cab: ["Fecha", "Concepto", "Divers", "Adventure"],
                    filas: [
                      ["Al reservar", "Anticipo para apartar tu lugar", "$2,000", "$2,000"],
                      ["20 nov 2026", "Segundo pago", "$6,500", "$6,500"],
                      ["20 ene 2027", "Tercer pago", "$6,500", "$6,000"],
                      ["20 mar 2027", "Cuarto pago", "$6,990", "$6,490"],
                      ["1 al 15 abr 2027", "Quinto pago", "$2,600", "$2,600"],
                      ["1 al 7 may 2027", "Sexto pago", "$5,400", "$5,400"],
                      ["**Total**", "", "**$29,990**", "**$28,990**"],
                    ],
                  } },
                  { plan: "early", moneda: "EUR", titulo: "Early Bird – Euros (EUR)", tabla: {
                    etiqueta: "Calendario de pagos Early Bird en euros",
                    cab: ["Fecha", "Concepto", "Divers", "Adventure"],
                    filas: [
                      ["Al reservar", "Anticipo para apartar tu lugar", "€100", "€100"],
                      ["20 nov 2026", "Segundo pago", "€300", "€300"],
                      ["20 ene 2027", "Tercer pago", "€300", "€300"],
                      ["20 mar 2027", "Cuarto pago", "€350", "€300"],
                      ["1 al 15 abr 2027", "Quinto pago", "€130", "€130"],
                      ["1 al 7 may 2027", "Sexto pago", "€300", "€300"],
                      ["**Total**", "", "**€1,480**", "**€1,430**"],
                    ],
                  } },
                  { plan: "regular", moneda: "MXN", titulo: "Precio regular – Pesos mexicanos (MXN)", tabla: {
                    etiqueta: "Calendario de pagos de precio regular en pesos mexicanos",
                    cab: ["Fecha", "Concepto", "Divers", "Adventure"],
                    filas: [
                      ["Al reservar", "Primer pago", "$14,000", "$13,500"],
                      ["20 mar 2027", "Segundo pago", "$13,000", "$12,500"],
                      ["1 al 15 abr 2027", "Tercer pago", "$2,600", "$2,600"],
                      ["1 al 7 may 2027", "Cuarto pago", "$5,400", "$5,400"],
                      ["**Total**", "", "**$35,000**", "**$34,000**"],
                    ],
                  } },
                  { plan: "regular", moneda: "EUR", titulo: "Precio regular – Euros (EUR)", tabla: {
                    etiqueta: "Calendario de pagos de precio regular en euros",
                    cab: ["Fecha", "Concepto", "Divers", "Adventure"],
                    filas: [
                      ["Al reservar", "Primer pago", "€700", "€650"],
                      ["20 mar 2027", "Segundo pago", "€600", "€600"],
                      ["1 al 15 abr 2027", "Tercer pago", "€130", "€130"],
                      ["1 al 7 may 2027", "Cuarto pago", "€300", "€300"],
                      ["**Total**", "", "**€1,730**", "**€1,680**"],
                    ],
                  } },
                ],
            } },
          ],
        },
        {
          titulo: "Política de pagos",
          contenido: [
            { ul: [
              "Para reservar es necesario aprobar el test de afinidad VOIA y pagar el anticipo o el primer pago.",
              "Si reservas después de alguna fecha de pago, pagas en ese momento el monto acumulado hasta esa fecha. Por ejemplo, un Early Bird que reserva en diciembre paga $8,500 MXN al reservar.",
              "Viajeros en México pagan en pesos (MXN); viajeros fuera de México pagan en euros (EUR). Los montos se fijan al reservar y no cambian por el tipo de cambio.",
              "Si un pago no se realiza a tiempo, VOIA puede liberar tu lugar después de avisarte por escrito con 7 días naturales para ponerte al corriente. En ese caso se aplican las penalidades de cancelación vigentes.",
            ] },
          ],
        },
        {
          titulo: "Política de cancelación",
          contenido: [
            { h: "Si cancelas tú" },
            { p: "La cancelación debe solicitarse por correo a voia.viajar@gmail.com. La fecha en que recibimos tu correo determina la penalidad." },
            { p: "**Servicios VOIA**. La penalidad es un porcentaje del precio total de estos servicios." },
            { tabla: {
                etiqueta: "Penalidades de cancelación de los servicios VOIA",
                cab: ["Fecha de cancelación", "Penalidad"],
                filas: [
                  ["Hasta el 30 nov 2026", "Se pierde el anticipo ($2,000 MXN / €100)"],
                  ["Del 1 dic 2026 al 20 ene 2027", "35% del precio total de los servicios VOIA"],
                  ["Del 21 ene al 22 mar 2027", "50% del precio total de los servicios VOIA"],
                  ["Desde el 23 mar 2027", "100% del precio total de los servicios VOIA"],
                ],
            } },
            { p: "**Pagos de abril y mayo** (pagos 5 y 6 en Early Bird; pagos 3 y 4 en precio regular)" },
            { ul: [
              "Si cancelas antes de esas fechas de pago, no se cobran.",
              "Si ya los pagaste pero VOIA todavía no los ha pagado al proveedor, se te devuelven completos.",
              "Si VOIA ya los pagó al proveedor, solo se devuelve lo que el proveedor reembolse.",
            ] },
            { h: "Crédito VOIA" },
            { p: "Si cancelas hasta el 30 de noviembre de 2026, en lugar de perder el anticipo puedes convertir el 100% de lo que hayas pagado en Crédito VOIA. El crédito es válido durante 18 meses para cualquier viaje VOIA. Es personal y no se reembolsa en efectivo." },
            { h: "Ceder tu lugar" },
            { p: "Puedes ceder tu lugar a otra persona sin penalidad hasta el 22 de abril de 2027, siempre que:" },
            { ul: [
              "la nueva persona apruebe el test de afinidad VOIA;",
              "los proveedores permitan el cambio de nombre;",
              "se cubran los cargos que los proveedores cobren por el cambio.",
            ] },
            { h: "Mínimo de viajeros" },
            { p: "El viaje sale con un mínimo de 4 viajeros. Si no se alcanza el mínimo, VOIA puede cancelar el viaje y te devolverá el 100% de lo pagado, o lo convertirá en Crédito VOIA si así lo prefieres." },
            { h: "Si cancela VOIA" },
            { ul: [
              "**Por decisión de VOIA:** se devuelve el 100% de lo pagado.",
              "**Por causas de fuerza mayor** (desastres naturales, alertas oficiales de viaje, cierres de fronteras, epidemias, conflictos o fenómenos meteorológicos graves), puedes elegir entre Crédito VOIA por el 100% de lo pagado, válido 18 meses, o el reembolso de lo pagado menos los costos que VOIA haya pagado a proveedores y no pueda recuperar, con la documentación correspondiente.",
            ] },
          ],
        },
        {
          titulo: "Durante el viaje",
          contenido: [
            { h: "Cambios en el itinerario" },
            { p: "La naturaleza manda. VOIA puede ajustar el itinerario por clima, condiciones del mar, seguridad, bienestar de la fauna o decisiones de las autoridades." },
            { ul: [
              "Si una actividad se sustituye por otra equivalente, no hay reembolso.",
              "Si VOIA cancela una actividad sin causa climática, de seguridad o de fuerza mayor, se devuelve su valor o se convierte en Crédito VOIA.",
              "No hay reembolso por actividades, comidas o noches que decidas no utilizar.",
            ] },
            { h: "Seguro de viaje obligatorio" },
            { p: "Debe estar vigente del 22 de mayo al 5 de junio de 2027 y cubrir gastos médicos, evacuación y repatriación. Te recomendamos que incluya cobertura de cancelación. Envíanos tu póliza a más tardar el 22 de abril de 2027." },
            { aviso: "Si contratas tu seguro con Heymondo desde este enlace, se aplica automáticamente un 5% de descuento: [contrata tu seguro aquí](https://heymondo.com/es?utm_medium=Afiliado&utm_source=ALEFERREYRON&utm_campaign=PRINCIPAL&cod_descuento=ALEFERREYRON&ag_campaign=ENTRADA&agencia=vEMQ54QxQboWxl2j8iwMMOoCTiVH3IqvyJHhBQm3)." },
            { h: "Vuelos y documentación" },
            { p: "Los vuelos no están incluidos. Cada viajero es responsable de sus vuelos, pasaporte, visa y requisitos de entrada a Indonesia. Los retrasos o cancelaciones de las aerolíneas, y los gastos que generen, corren por cuenta del viajero." },
            { h: "Habitaciones" },
            { p: "Las habitaciones se asignan según el orden en que cada viajero liquide su viaje." },
          ],
        },
      ],
    },
  },
  {
    slug: "filipinas",
    grupo: "internacionales",
    nombre: "Filipinas",
    meta: "Coron y El Nido · 15 días",
    duracion: "15 días / 14 noches",
    ubicacion: "Coron y El Nido, Palawan",
    fechas: "No disponibles por el momento",
    marcaAgua: "AF Photography", // aparece en chiquito al pasar el cursor sobre una foto de la galería (solo escritorio)
    tagline: "De Coron a El Nido: lagunas, naufragios y expedición por islas remotas",
    tile: "media/filipinasmedia/coron1-tile.jpg",
    tilePos: "50% 45%",
    hero: "photo-1591049014083-3339a6fe59eb", // portada de la página (no es de la galería)
    citaFoto: "photo-1695051702427-1c24ce3682e7", // fondo de la frase (no es de la galería)
    galeria: [
      { src: "media/filipinasmedia/web/filipinasmedia-01.jpg", w: 1138, h: 640, alt: "Vista aérea de una laguna escondida entre acantilados de piedra caliza" },
      { src: "media/filipinasmedia/web/filipinasmedia-02.jpg", w: 427, h: 640, alt: "Pareja de pie en la proa de una banca frente al mar turquesa" },
      { src: "media/filipinasmedia/web/filipinasmedia-03.jpg", w: 360, h: 640, alt: "Vista aérea de una banca filipina navegando sobre el mar" },
      { src: "media/filipinasmedia/web/filipinasmedia-04.jpg", w: 1138, h: 640, alt: "Vista aérea de islotes y arrecifes desde el aire" },
      { src: "media/filipinasmedia/web/filipinasmedia-05.jpg", w: 427, h: 640, alt: "Mujer recostada sobre el balancín de una banca, con el mar transparente debajo" },
      { src: "media/filipinasmedia/web/filipinasmedia-06.jpg", w: 360, h: 640, alt: "Vista aérea de una laguna escondida entre formaciones rocosas" },
      { src: "media/filipinasmedia/web/filipinasmedia-07.jpg", w: 1138, h: 640, alt: "Vista aérea de islas de piedra caliza con una plataforma flotante" },
      { src: "media/filipinasmedia/web/filipinasmedia-08.jpg", w: 360, h: 640, alt: "Vista aérea de una laguna circular con dos plataformas flotantes" },
      { src: "media/filipinasmedia/web/filipinasmedia-09.jpg", w: 960, h: 640, alt: "Pareja sentada en la proa de una banca sobre un mar en calma" },
      { src: "media/filipinasmedia/web/filipinasmedia-10.jpg", w: 360, h: 640, alt: "Vista aérea de una banca anclada junto a acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-11.jpg", w: 960, h: 640, alt: "Hombre de pie en la proa de una banca frente a acantilados de piedra caliza" },
      { src: "media/filipinasmedia/web/filipinasmedia-12.jpg", w: 360, h: 640, alt: "Vista aérea de una laguna y un lago rodeados de acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-13.jpg", w: 360, h: 640, alt: "Vista aérea de dos lagunas conectadas entre pequeñas islas" },
      { src: "media/filipinasmedia/web/filipinasmedia-14.jpg", w: 1138, h: 640, alt: "Vista aérea de una laguna con cabañas flotantes y bancas ancladas" },
      { src: "media/filipinasmedia/web/filipinasmedia-15.jpg", w: 427, h: 640, alt: "Hombre en una banca junto a una cabaña sobre pilotes en aguas transparentes" },
      { src: "media/filipinasmedia/web/filipinasmedia-16.jpg", w: 1138, h: 640, alt: "Vista aérea de dos bancas en un canal estrecho entre acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-17.jpg", w: 360, h: 640, alt: "Vista aérea de una laguna con una plataforma flotante" },
      { src: "media/filipinasmedia/web/filipinasmedia-18.jpg", w: 960, h: 640, alt: "Mujer remando sobre aguas turquesas rodeada de acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-19.jpg", w: 1138, h: 640, alt: "Vista aérea de una playa con acantilados de piedra caliza y una banca" },
      { src: "media/filipinasmedia/web/filipinasmedia-20.jpg", w: 1138, h: 640, alt: "Vista aérea de varias lagunas entre islas verdes" },
      { src: "media/filipinasmedia/web/filipinasmedia-21.jpg", w: 960, h: 640, alt: "Silueta de un pescador remando al atardecer" },
      { src: "media/filipinasmedia/web/filipinasmedia-22.jpg", w: 1138, h: 640, alt: "Vista aérea de una banca anclada sobre un arrecife de coral" },
      { src: "media/filipinasmedia/web/filipinasmedia-23.jpg", w: 960, h: 640, alt: "Reflejo de los acantilados de piedra caliza sobre el agua en calma" },
      { src: "media/filipinasmedia/web/filipinasmedia-24.jpg", w: 1138, h: 640, alt: "Vista aérea de una laguna pequeña con una persona nadando, rodeada de acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-25.jpg", w: 360, h: 640, alt: "Dos personas caminando por una playa rocosa bajo acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-26.jpg", w: 1138, h: 640, alt: "Bancas ancladas en una cala de aguas turquesas" },
      { src: "media/filipinasmedia/web/filipinasmedia-27.jpg", w: 1138, h: 640, alt: "Vista aérea de una pequeña isla con playa en mar abierto" },
      { src: "media/filipinasmedia/web/filipinasmedia-28.jpg", w: 426, h: 640, alt: "Hombre caminando por un muelle de madera sobre aguas transparentes" },
      { src: "media/filipinasmedia/web/filipinasmedia-29.jpg", w: 360, h: 640, alt: "Vista aérea de una laguna escondida con una persona nadando" },
      { src: "media/filipinasmedia/web/filipinasmedia-30.jpg", w: 426, h: 640, alt: "Mujer sentada en la proa de una banca rodeada de acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-31.jpg", w: 960, h: 640, alt: "Muelle de madera hacia una laguna en calma rodeada de acantilados" },
      { src: "media/filipinasmedia/web/filipinasmedia-32.jpg", w: 1138, h: 640, alt: "Vista aérea de una laguna con un camastro flotante" },
      { src: "media/filipinasmedia/web/filipinasmedia-33.jpg", w: 919, h: 640, alt: "Bancas en un muelle al atardecer" },
      { src: "media/filipinasmedia/web/filipinasmedia-34.jpg", w: 427, h: 640, alt: "Vista aérea de agua transparente y arrecife junto a una isla" },
      { src: "media/filipinasmedia/web/filipinasmedia-35.jpg", w: 360, h: 640, alt: "Banca anclada sobre un arrecife transparente junto a una cabaña sobre pilotes" },
      { src: "media/filipinasmedia/web/filipinasmedia-36.jpg", w: 1138, h: 640, alt: "Vista aérea de bancas ancladas sobre un arrecife junto a una pequeña isla" },
      { src: "media/filipinasmedia/web/filipinasmedia-37.jpg", w: 960, h: 640, alt: "Hombre sentado en la proa de una banca sobre aguas transparentes" },
      { src: "media/filipinasmedia/web/filipinasmedia-38.jpg", w: 427, h: 640, alt: "Pareja abrazada de pie sobre una playa de arena blanca" },
      { src: "media/filipinasmedia/web/filipinasmedia-39.jpg", w: 960, h: 640, alt: "Vista del agua transparente y los acantilados desde una banca" },
      { src: "media/filipinasmedia/web/filipinasmedia-40.jpg", w: 960, h: 640, alt: "Arrecife transparente junto a imponentes acantilados de piedra caliza" },
      { src: "media/filipinasmedia/web/filipinasmedia-41.jpg", w: 427, h: 640, alt: "Mujer de pie en la proa de una banca, con los brazos abiertos" },
      { src: "media/filipinasmedia/web/filipinasmedia-42.jpg", w: 427, h: 640, alt: "Silueta de dos hombres en una banca al atardecer, cerca de un muelle" },
    ],
    descripcion: [
      "Filipinas es un archipiélago de más de siete mil islas, y el norte de Palawan reúne algunos de sus paisajes más impresionantes: acantilados de roca caliza cubiertos de selva, lagunas de agua turquesa, naufragios y arrecifes llenos de vida.",
      "En quince días vamos de Coron a El Nido. Primero recorremos Coron, con sus lagos, lagunas y arrecifes, en tours privados. Después hacemos una expedición de tres días y dos noches en campamento por las islas remotas de Culion y Linapacan. Terminamos en El Nido, con días de playa, lagunas y descanso.",
      "Los tours dependen del clima y del mar, por eso incluimos días de reserva.",
    ],
    cita: "De Coron a El Nido, una aventura atravesando islas vírgenes y paisajes fantásticos.",
    destacados: [
      "Lagos y lagunas de Coron: Kayangan, Twin Lagoon y Barracuda Lake",
      "Snorkel entre naufragios y arrecifes",
      "Expedición de 3 días con campamento en las islas de Linapacan",
      "Big Lagoon, Secret Lagoon y Hidden Beach en El Nido",
      "Días de descanso y de reserva por si el clima cambia los planes",
    ],
    itinerario: [
      { dia: 1, titulo: "Llegada a Coron", lugar: "Coron", plan: ["Llegada al aeropuerto de Busuanga–Coron (USU) y traslado al hotel.", "Check-in y paseo tranquilo por Coron Town."] },
      { dia: 2, titulo: "Lagos y lagunas de Coron", lugar: "Coron", plan: ["Tour privado por Kayangan Lake, Twin Lagoon, Pusod Lagoon y Barracuda Lake."] },
      { dia: 3, titulo: "Snorkel y naufragio", lugar: "Coron", plan: ["Tour privado con snorkel en Skeleton Wreck, Smith Point y Smith Beach / Coral Garden."] },
      { dia: 4, titulo: "Arrecifes y naufragios", lugar: "Coron", plan: ["Tour de arrecifes y naufragios: Lusong Gunboat, Lusong Coral Garden, East Tangat Wreck y Pass Island."] },
      { dia: 5, titulo: "Siete Pecados y día de reserva", lugar: "Coron", plan: ["Salida temprano para hacer snorkel en Siete Pecados Marine Park.", "Tarde libre, con Mount Tapyas o Maquinit Hot Springs como opciones.", "Este día también sirve de reserva si algún tour se cancela."] },
      { dia: 6, titulo: "De Coron a Linapacan", lugar: "Expedición · día 1", plan: ["Salida de Coron y navegación hacia Culion y Linapacan, con paradas variables de playa y snorkel.", "Primera noche en campamento."] },
      { dia: 7, titulo: "Islas de Linapacan", lugar: "Expedición · día 2", plan: ["Día completo entre islas remotas, arrecifes y playas, con posibles visitas a comunidades locales.", "Segunda noche en campamento."] },
      { dia: 8, titulo: "Llegada a El Nido", lugar: "Expedición · día 3", plan: ["Últimas paradas de playa y snorkel.", "Llegada a El Nido durante la tarde o al final del día."] },
      { dia: 9, titulo: "Descanso y Lio Beach", lugar: "El Nido", plan: ["Mañana libre para descansar y hacer lavandería.", "Tarde en Lio Beach y cena en El Nido Town o Corong-Corong."] },
      { dia: 10, titulo: "Tour A", lugar: "El Nido", plan: ["Big Lagoon, Secret Lagoon, Shimizu Island y Seven Commandos Beach.", "Payong-Payong, si está operativo."] },
      { dia: 11, titulo: "Descanso y Las Cabañas", lugar: "El Nido", plan: ["Mañana libre.", "Llegada a Las Cabañas / Marimegmeg entre 3:00 y 4:00 pm para disfrutar la playa, el atardecer y la cena."] },
      { dia: 12, titulo: "Tour C", lugar: "El Nido", plan: ["Helicopter Island, Hidden Beach, Cagbatang Island (o un snorkel equivalente), Secret Beach y Matinloc Shrine."] },
      { dia: 13, titulo: "Nacpan y norte de El Nido", lugar: "El Nido", plan: ["Día en Nacpan Beach.", "Continuamos a Duli Beach si el tiempo, el camino y el ritmo del grupo lo permiten."] },
      { dia: 14, titulo: "Día libre o de reserva", lugar: "El Nido", plan: ["Si algún tour se canceló, recuperamos el Tour A o el C.", "Si todo salió como estaba previsto: descanso, buceo opcional, kayak, Lio Beach o una segunda visita a Las Cabañas."] },
      { dia: 15, titulo: "Salida", lugar: "El Nido – Aeropuerto", plan: ["Check-out y traslado al aeropuerto de El Nido–Lio (ENI)."] },
    ],
    nota: "Los tours dependen del clima y de las condiciones del mar. Los días de reserva permiten recuperar salidas canceladas.",
  },
  {
    slug: "raja-ampat",
    grupo: "internacionales",
    nombre: "Raja Ampat",
    meta: "Próximamente",
    proximamente: true,
    duracion: "15 días",
    ubicacion: "Papúa Occidental, Indonesia",
    tagline: "El arrecife más diverso del planeta",
    tile: "photo-1703769605297-cc74106244d9",
    galeria: [
      "photo-1703769605297-cc74106244d9",
      "photo-1702664045144-8c97b3034d26",
      "photo-1516690561799-46d8f74f9abf",
    ],
    descripcion: [
      "Raja Ampat, en Papúa Occidental, es un conjunto de cientos de islas cubiertas de selva sobre arrecifes de coral.",
    ],
    cita: "Donde el arrecife más diverso del planeta se encuentra con la selva.",
    itinerario: null,
  },
  {
    slug: "sumatra",
    grupo: "internacionales",
    nombre: "Sumatra",
    meta: "Batu Katak y Bukit Lawang · 6 días",
    duracion: "6 días / 5 noches",
    ubicacion: "Batu Katak, Bukit Lawang y Medan, Sumatra",
    fechas: "No disponibles por el momento",
    marcaAgua: "AF Photography", // aparece en chiquito al pasar el cursor sobre una foto de la galería (solo escritorio)
    tagline: "Trekking en la selva y orangutanes en Sumatra",
    tile: "media/sumatramedia/orangutan1-tile.jpg",
    tilePos: "55% 40%",
    hero: "media/sumatramedia/orangutan1-hero.jpg", // portada de la página
    heroPos: "55% 35%", // qué parte de la foto se ve al recortarla (horizontal vertical)
    citaFoto: "photo-1723153247780-02e191e1dd0c",
    galeria: [
      { src: "media/sumatramedia/web/sumatragaleria-1.jpg", w: 427, h: 640, alt: "Orangután colgado de un árbol en la selva de Sumatra" },
      { src: "media/sumatramedia/web/sumatragaleria-02.jpg", w: 427, h: 640, alt: "Orangután trepando entre las ramas de la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-03.jpg", w: 960, h: 640, alt: "Guía local junto a una flor gigante en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-04.jpg", w: 427, h: 640, alt: "Orangután de pelaje rojizo sobre un tronco" },
      { src: "media/sumatramedia/web/sumatragaleria-05.jpg", w: 960, h: 640, alt: "Viajera recostada sobre unas lianas en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-06.jpg", w: 427, h: 640, alt: "Guías cortando una sandía sobre el suelo de la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-07.jpg", w: 921, h: 640, alt: "Frutas tropicales servidas sobre hojas de plátano" },
      { src: "media/sumatramedia/web/sumatragaleria-08.jpg", w: 480, h: 640, alt: "Guía y dos viajeros agachados junto a un plato de frutas en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-09.jpg", w: 427, h: 640, alt: "Viajera frente a un campamento de lona en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-10.jpg", w: 427, h: 640, alt: "Insecto de colores brillantes sobre un tronco" },
      { src: "media/sumatramedia/web/sumatragaleria-12.jpg", w: 960, h: 640, alt: "Pareja de viajeros frente a un campamento en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-13.jpg", w: 427, h: 640, alt: "Viajera mirando hacia la copa de los árboles" },
      { src: "media/sumatramedia/web/sumatragaleria-14.jpg", w: 427, h: 640, alt: "Viajera frente a una flor gigante en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-15.jpg", w: 427, h: 640, alt: "Macaco sentado entre la vegetación" },
      { src: "media/sumatramedia/web/sumatragaleria-16.jpg", w: 427, h: 640, alt: "Sendero de selva entre árboles enormes" },
      { src: "media/sumatramedia/web/sumatragaleria-17.jpg", w: 960, h: 640, alt: "Comida local servida sobre hojas de plátano" },
      { src: "media/sumatramedia/web/sumatragaleria-18.jpg", w: 427, h: 640, alt: "Papaya, naranja y fruta del dragón sobre hojas de plátano" },
      { src: "media/sumatramedia/web/sumatragaleria-19.jpg", w: 427, h: 640, alt: "Dos viajeros preparando frutas sobre hojas en el suelo de la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-20.jpg", w: 427, h: 640, alt: "Viajero caminando por un sendero de la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-21.jpg", w: 427, h: 640, alt: "Árbol gigante con raíces enormes en la selva" },
      { src: "media/sumatramedia/web/sumatragaleria-22.jpg", w: 960, h: 640, alt: "Viajero cruzando un arroyo en la selva" },
    ],
    descripcion: [
      "Sumatra guarda algunas de las selvas tropicales más importantes del planeta y es hogar del orangután, el tigre y el elefante de Sumatra, tres especies en peligro. El turismo responsable puede ayudar a protegerlas.",
      "Este viaje de seis días recorre dos zonas de selva. En Batu Katak caminamos con guía para buscar orangutanes y monos completamente salvajes en su hábitat natural. En Bukit Lawang, donde los encuentros suelen ser más sencillos, observamos orangutanes semisalvajes. En total son cinco noches: dos en lodge, dos en la selva y una en Medan.",
      "Los animales viven en libertad y no se puede asegurar cuándo o cómo aparecerán. Observamos siempre con respeto y a distancia.",
    ],
    cita: "Una de las dos únicas islas del mundo donde los orangutanes aún viven en libertad.",
    destacados: [
      "Trekking en selva virgen en Batu Katak",
      "Orangutanes y monos salvajes en su hábitat natural",
      "Orangutanes semisalvajes en Bukit Lawang",
      "Noches en lodge y en plena selva",
    ],
    itinerario: [
      { dia: 1, titulo: "Llegada y traslado", lugar: "Medan – Batu Katak", plan: ["Llegada al aeropuerto de Medan, encuentro con el conductor y traslado por carretera de unas 4 horas a Batu Katak."] },
      { dia: 2, titulo: "Trekking en selva virgen", lugar: "Batu Katak", plan: ["Salida con guía hacia la selva de Batu Katak para buscar orangutanes y monos completamente salvajes en su hábitat natural."] },
      { dia: 3, titulo: "Última caminata y cambio de base", lugar: "Batu Katak – Bukit Lawang", plan: ["Recorrido adicional por la selva de Batu Katak y regreso al lodge en jungle taxi.", "Cambio de base hacia Bukit Lawang."] },
      { dia: 4, titulo: "Orangutanes semisalvajes", lugar: "Bukit Lawang", plan: ["Primer día de trekking por la selva de Bukit Lawang para observar orangutanes semisalvajes.", "En esta zona los encuentros suelen ser más sencillos y frecuentes que en Batu Katak."] },
      { dia: 5, titulo: "Fin del trekking y regreso", lugar: "Bukit Lawang – Medan", plan: ["Último recorrido por la selva durante la mañana.", "Regreso a Bukit Lawang en jungle taxi hacia el mediodía y traslado a Medan."] },
      { dia: 6, titulo: "Vuelo de regreso", lugar: "Medan", plan: ["Check-out, traslado al aeropuerto y vuelo de regreso."] },
    ],
    nota: "Los avistamientos de fauna silvestre no están garantizados.",
  },
  {
    slug: "komodo",
    grupo: "internacionales",
    nombre: "Komodo",
    meta: "Liveaboard y buceo · 6 días",
    duracion: "6 días / 5 noches",
    ubicacion: "Parque Nacional de Komodo y Labuan Bajo",
    fechas: "No disponibles por el momento",
    marcaAgua: "AF Photography", // aparece en chiquito al pasar el cursor sobre una foto de la galería (solo escritorio)
    tagline: "Liveaboard, dragones de Komodo, mantas y buceo",
    tile: "media/komodomedia/web/komodogaleria-01-tile.jpg",
    tilePos: "58% 50%",
    hero: "media/komodomedia/web/komodogaleria-01-hero.jpg", // portada de la página
    citaFoto: "photo-1657788405193-c2039edaad6b", // fondo de la frase (no es de la galería)
    galeria: [
      { src: "media/komodomedia/web/komodogaleria-01.jpg", w: 960, h: 640, alt: "Vista desde un mirador sobre bahías de arena y colinas verdes" },
      { src: "media/komodomedia/web/komodogaleria-02.jpg", w: 1138, h: 640, alt: "Vista aérea de una bahía azul con veleros y arrecife turquesa" },
      { src: "media/komodomedia/web/komodogaleria-03.jpg", w: 960, h: 640, alt: "Pareja sentada en una roca frente a bahías y colinas verdes" },
      { src: "media/komodomedia/web/komodogaleria-04.jpg", w: 960, h: 640, alt: "Barco tradicional de madera sobre el mar al atardecer" },
      { src: "media/komodomedia/web/komodogaleria-05.jpg", w: 1138, h: 640, alt: "Vista aérea de una isla seca con playa y arrecife turquesa" },
      { src: "media/komodomedia/web/komodogaleria-06.jpg", w: 427, h: 640, alt: "Silueta de dos personas en la cubierta de un barco al atardecer" },
      { src: "media/komodomedia/web/komodogaleria-07.jpg", w: 426, h: 640, alt: "Dragón de Komodo entre la vegetación" },
      { src: "media/komodomedia/web/komodogaleria-08.jpg", w: 960, h: 640, alt: "Buceador sobre un arrecife de coral en aguas profundas" },
      { src: "media/komodomedia/web/komodogaleria-09.jpg", w: 1138, h: 640, alt: "Vista aérea de una bahía con barcos junto a una isla" },
      { src: "media/komodomedia/web/komodogaleria-10.jpg", w: 960, h: 640, alt: "Buceador junto a un arrecife de coral" },
      { src: "media/komodomedia/web/komodogaleria-11.jpg", w: 960, h: 640, alt: "Dragón de Komodo descansando a la sombra" },
      { src: "media/komodomedia/web/komodogaleria-12.jpg", w: 360, h: 640, alt: "Vista aérea de una bahía con barcos y arrecife turquesa" },
      { src: "media/komodomedia/web/komodogaleria-13.jpg", w: 360, h: 640, alt: "Vista aérea de una persona en el agua cristalina junto a una playa de arena rosada" },
      { src: "media/komodomedia/web/komodogaleria-14.jpg", w: 960, h: 640, alt: "Silueta de un barco de madera con la luz del atardecer" },
      { src: "media/komodomedia/web/komodogaleria-15.jpg", w: 360, h: 640, alt: "Barco navegando junto a una isla verde en aguas turquesa" },
      { src: "media/komodomedia/web/komodogaleria-16.jpg", w: 427, h: 640, alt: "Mujer de pie en un mirador con vista a las bahías" },
      { src: "media/komodomedia/web/komodogaleria-17.jpg", w: 960, h: 640, alt: "Playa de arena oscura con colinas y barcos en la bahía" },
      { src: "media/komodomedia/web/komodogaleria-18.jpg", w: 960, h: 640, alt: "Dragón de Komodo entre la vegetación" },
      { src: "media/komodomedia/web/komodogaleria-19.jpg", w: 427, h: 640, alt: "Viajero sentado en una roca frente a una bahía al amanecer" },
      { src: "media/komodomedia/web/komodogaleria-20.jpg", w: 360, h: 640, alt: "Vista aérea de una bahía con veleros" },
      { src: "media/komodomedia/web/komodogaleria-21.jpg", w: 960, h: 640, alt: "Tres viajeros sentados en un mirador viendo el atardecer" },
      { src: "media/komodomedia/web/komodogaleria-22.jpg", w: 1138, h: 640, alt: "Barco navegando sobre aguas turquesa junto a una isla" },
      { src: "media/komodomedia/web/komodogaleria-23.jpg", w: 360, h: 640, alt: "Vista aérea de una isla con arrecife turquesa" },
      { src: "media/komodomedia/web/komodogaleria-24.jpg", w: 427, h: 640, alt: "Pareja abrazada en un mirador sobre bahías de arena" },
      { src: "media/komodomedia/web/komodogaleria-25.jpg", w: 960, h: 640, alt: "Vista de bahías y colinas verdes desde un mirador" },
      { src: "media/komodomedia/web/komodogaleria-26.jpg", w: 1138, h: 640, alt: "Bote pequeño sobre aguas transparentes junto a una playa rosada" },
      { src: "media/komodomedia/web/komodogaleria-27.jpg", w: 1138, h: 640, alt: "Vista aérea de una isla y su arrecife turquesa" },
      { src: "media/komodomedia/web/komodogaleria-28.jpg", w: 427, h: 640, alt: "Grupo caminando con un guía por un sendero entre colinas" },
      { src: "media/komodomedia/web/komodogaleria-29.jpg", w: 960, h: 640, alt: "Silueta de dos personas al atardecer" },
      { src: "media/komodomedia/web/komodogaleria-30.jpg", w: 426, h: 640, alt: "Pareja posando en la proa de un barco frente a una isla" },
      { src: "media/komodomedia/web/komodogaleria-31.jpg", w: 427, h: 640, alt: "Dos barcos sobre el mar azul con islas al fondo" },
      { src: "media/komodomedia/web/komodogaleria-32.jpg", w: 427, h: 640, alt: "Tiburón pequeño nadando en aguas poco profundas" },
      { src: "media/komodomedia/web/komodogaleria-33.jpg", w: 427, h: 640, alt: "Silueta de dos personas al atardecer con aves en el cielo" },
      { src: "media/komodomedia/web/komodogaleria-34.jpg", w: 427, h: 640, alt: "Silueta de un barco de madera al atardecer" },
      { src: "media/komodomedia/web/komodogaleria-35.jpg", w: 960, h: 640, alt: "Amanecer sobre bahías y colinas verdes" },
      { src: "media/komodomedia/web/komodogaleria-36.jpg", w: 426, h: 640, alt: "Tortuga marina nadando en aguas profundas, vista desde arriba" },
      { src: "media/komodomedia/web/komodogaleria-37.jpg", w: 426, h: 640, alt: "Mujer sentada en una roca frente a la bahía al amanecer" },
      { src: "media/komodomedia/web/komodogaleria-38.jpg", w: 960, h: 640, alt: "Guía del parque saludando frente a una oficina" },
      { src: "media/komodomedia/web/komodogaleria-39.jpg", w: 427, h: 640, alt: "Silueta de una persona al atardecer con aves en el cielo" },
      { src: "media/komodomedia/web/komodogaleria-40.jpg", w: 960, h: 640, alt: "Dragón de Komodo en un claro de tierra" },
      { src: "media/komodomedia/web/komodogaleria-41.jpg", w: 960, h: 640, alt: "Colinas verdes de una isla vistas desde el mar" },
      { src: "media/komodomedia/web/komodogaleria-42.jpg", w: 960, h: 640, alt: "Buceador sobre un arrecife de coral" },
      { src: "media/komodomedia/web/komodogaleria-43.jpg", w: 426, h: 640, alt: "Barco de madera al atardecer" },
      { src: "media/komodomedia/web/komodogaleria-44.jpg", w: 960, h: 640, alt: "Atardecer naranja sobre el mar" },
      { src: "media/komodomedia/web/komodogaleria-45.jpg", w: 427, h: 640, alt: "Mujer de pie en un mirador sobre las bahías" },
      { src: "media/komodomedia/web/komodogaleria-46.jpg", w: 960, h: 640, alt: "Silueta de un viajero mirando el atardecer, con aves volando" },
      { src: "media/komodomedia/web/komodogaleria-47.jpg", w: 427, h: 640, alt: "Isla verde en forma de cono vista desde el mar" },
      { src: "media/komodomedia/web/komodogaleria-48.jpg", w: 427, h: 640, alt: "Tiburón pequeño en aguas poco profundas sobre el fondo de arena" },
      { src: "media/komodomedia/web/komodogaleria-49.jpg", w: 426, h: 640, alt: "Tortuga marina sobre un arrecife de coral" },
      { src: "media/komodomedia/web/komodogaleria-50.jpg", w: 960, h: 640, alt: "Dragón de Komodo en un claro de tierra" },
      { src: "media/komodomedia/web/komodogaleria-51.jpg", w: 427, h: 640, alt: "Pareja sentada en un mirador sobre las bahías" },
    ],
    descripcion: [
      "Las islas de Komodo son el único lugar del mundo donde viven los dragones de Komodo. Su parque nacional guarda colinas secas, playas de arena rosa y aguas con corrientes que atraen a mantas y tortugas.",
      "Este viaje de seis días combina dos noches en un barco (liveaboard) por el parque, con paradas de snorkel, caminatas y un atardecer con miles de zorros voladores, y tres noches en Labuan Bajo, donde hay un día completo de buceo con tres inmersiones y un día para descansar.",
      "Los puntos de snorkel y de buceo se eligen según las corrientes, las condiciones del mar y el nivel del grupo.",
    ],
    cita: "Navegar de isla en isla, entre dragones en tierra y vida salvaje bajo el mar.",
    destacados: [
      "Dos noches en un liveaboard por el Parque Nacional de Komodo",
      "Mirador de la isla Padar y Pink Beach",
      "Trekking corto con ranger para buscar dragones de Komodo",
      "Snorkel en Manta Point",
      "Día de buceo con tres inmersiones",
    ],
    itinerario: [
      { dia: 1, titulo: "Inicio del liveaboard", lugar: "Labuan Bajo – barco", plan: ["Recogida en el hotel o el aeropuerto entre las 9:00 y las 11:00, traslado al puerto, embarque y salida.", "Kelor Island: caminata corta hasta el mirador, playa y snorkel.", "Manjarite Island: primer snorkel entre peces de colores.", "Kalong Island: navegación junto a los manglares y miles de zorros voladores al atardecer."] },
      { dia: 2, titulo: "Padar, Pink Beach y fauna marina", lugar: "Parque Nacional de Komodo", plan: ["Salida de madrugada hacia la isla Padar y caminata por escaleras hasta el mirador.", "Continuación hacia Pink Beach / Long Beach, con snorkel.", "Trekking corto con ranger en la isla Komodo para buscar dragones y observar fauna.", "Manta Point y, si las condiciones y tu nivel lo permiten, snorkel en Taka Makassar."] },
      { dia: 3, titulo: "Último snorkel y regreso", lugar: "Komodo – Labuan Bajo", plan: ["Snorkel en la isla Kanawa o en Sebayur, según la ruta y las condiciones, cerca de la playa o del jetty, y tiempo para descansar.", "Llegada a Labuan Bajo entre las 11:00 y las 13:00, desembarque, traslado y check-in en el hotel.", "Tarde libre."] },
      { dia: 4, titulo: "Día de buceo: 3 tanques", lugar: "Parque Nacional de Komodo", plan: ["Recogida a las 6:30 am y salida para hacer tres inmersiones en el parque.", "Desayuno, comida, café y agua incluidos.", "Los puntos de buceo se eligen según las corrientes, el mar y el nivel del grupo."] },
      { dia: 5, titulo: "Descanso y atardecer", lugar: "Labuan Bajo", plan: ["Día de recuperación después del buceo, con la mañana y las primeras horas de la tarde libres.", "Pequeña caminata por la tarde para ver el atardecer; el lugar se confirma según el clima y la logística."] },
      { dia: 6, titulo: "Vuelo de regreso", lugar: "Labuan Bajo", plan: ["Check-out, traslado al aeropuerto y vuelo de regreso.", "Programa el vuelo después de cumplir el intervalo de superficie recomendado tras el buceo."] },
    ],
    nota: "Los avistamientos de fauna silvestre no están garantizados. Los puntos de snorkel y buceo dependen de las condiciones del mar.",
  },
];

/* ---------------- Preguntas frecuentes (pie de página) ---------------- */
const FAQ = [
  {
    q: "¿Qué significa viajar de forma sostenible con VOIA?",
    a: "Significa cuidar tres cosas a la vez: los lugares que visitamos, las comunidades que nos reciben y la experiencia de quienes viajan. Por eso trabajamos con grupos pequeños, guías locales y operadores responsables, y evitamos las actividades que ponen en riesgo a los animales.",
  },
  {
    q: "¿Cómo sé si un viaje es para mí?",
    a: "¡Haz el test que encontrarás en el menú! Te ayudará a descubrir qué experiencias encajan mejor con tus intereses y tu forma de viajar. Si tienes dudas sobre el nivel de actividad o algún requisito específico, escríbenos y lo revisamos contigo.",
  },
  {
    q: "¿Me garantizan ver animales?",
    a: "No, y es mejor así. Son animales libres y sus movimientos dependen de la temporada, el clima y el mar. Elegimos las mejores épocas para cada destino, pero nunca alteramos el comportamiento de los animales para asegurar un avistamiento.",
  },
  {
    q: "¿Cómo reservo mi lugar?",
    a: "Escríbenos por WhatsApp con el destino y las fechas que te interesan. Te enviamos el itinerario completo, lo que incluye el viaje y los pasos para apartar tu lugar.",
  },
];
